### PR TITLE
toughIQ 30 node contribution

### PR DESCRIPTION
**Pull request by toughIQ**
30 DigitalOcean nodes by toughIQ

### CODE REVIEW

**Comment by chanwit** [comment]
I'll merge this ASAP @toughIQ 
Sorry for the delay

**Comment by toughIQ** [comment]
no problem. since there is a conflict right now, shall I rebase or will you just paste my line into README?

**Comment by chanwit** [comment]
It would be great if you can help rebasing it.
Sorry about that.

**Comment by chanwit** [comment]
Sorry for taking time to merge this.
LGTM thank you @toughIQ  !!!

**Pull request merged**
